# Generated by Django 5.2 on 2025-05-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_remove_reservation_hotel_name_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
